# Generated by Django 3.1 on 2021-10-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoSernacApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
