# Generated by Django 3.1 on 2021-11-14 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoSernacApp', '0006_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProyectoSernacApp.comentarios'),
        ),
    ]
