# Generated by Django 3.2.9 on 2021-11-19 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ProyectoSernacApp', '0008_auto_20211118_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
