# Generated by Django 3.2.9 on 2021-11-25 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoSernacApp', '0004_auto_20211115_2310'),
        ('ProyectoSernacApp', '0009_auto_20211119_0208'),
    ]

    operations = [
    ]
