# Generated by Django 3.2.9 on 2021-11-27 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoSernacApp', '0010_merge_0004_auto_20211115_2310_0009_auto_20211119_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesadmin',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
